### ISSUE TITLE
New name suggestion

### ISSUE THREAD

**Issue by unixorn** [TamCore/autoupdate-oh-my-zsh-plugins#1]
Since this works with oh-my-zsh and not other ZSH frameworks like [zgen](https://github.com/tarjoilija/zgen) or [antigen](https://github.com/zsh-users/antigen), I suggest you rename it to **autoupdate-oh-my-zsh-plugins**.

I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I'd prefer to do that after you rename it if you decide to do that.

Thanks

**Comment by TamCore** [comment]
I agree with you, therefore I've changed the name to autoupdate-oh-my-zsh-plugins, as you suggested.

**Comment by unixorn** [comment]
Added as of https://github.com/unixorn/awesome-zsh-plugins/pull/426
