### ISSUE TITLE
Upgrade function does not leave the last directory

### ISSUE THREAD

**Issue by PositivePaulo** [TamCore/autoupdate-oh-my-zsh-plugins#12]
It seems to me that the core function performing the upgrade itself goes
correctly in all git repositories of the `$ZSH_CUSTOM`, but does not change
back to the original working directory as of when calling the script.

To test this, I simply commented out the last line of the main script file, the
one unsetting local functions, and then directly:

```shell
$ source ./autoupdate.plugin.zsh
$ _upgrade_custom
<...>
```

This should call the upgrade function just like it does normally, but when
it is done, the shell is placed in the last updated plugin or theme, which
is undesirable in my opinion.

I think simply saving the `$PWD` before `cd` ing to upgrade plugins and
changing back to it after that is done should do the trick. Would a PR be
good for this?

Cheers.

**Comment by PositivePaulo** [comment]
This is now especially true in the current version using the upgrade
function directly or the all-in-one alias.

**Comment by TamCore** [comment]
Should be fixed now :)
