### ISSUE TITLE
Follow symlinks

### ISSUE THREAD

**Issue by ckotte** [TamCore/autoupdate-oh-my-zsh-plugins#13]
Could you replace ```find "${ZSH_CUSTOM}" -type d -name .git | while read d``` with ```find -L "${ZSH_CUSTOM}" -type d -name .git | while read d```?

I have all my plugins and themes symlinked to a folder that's synced (via Syncthing) to my other computers.

```
~/.oh-my-zsh/custom/plugins> ll                                                                                                                                                             
total 0
lrwxr-xr-x 1 user user 45 Jul  8 18:11 autoupdate -> ../../../.backup/oh-my-zsh/plugins/autoupdate
drwx------ 3 user user 96 Jul  8 16:49 example
lrwxr-xr-x 1 user user 54 Jul  8 18:11 zsh-autosuggestions -> ../../../.backup/oh-my-zsh/plugins/zsh-autosuggestions
lrwxr-xr-x 1 user user 50 Jul  8 18:11 zsh-completions -> ../../../.backup/oh-my-zsh/plugins/zsh-completions
lrwxr-xr-x 1 user user 58 Jul  8 18:11 zsh-syntax-highlighting -> ../../../.backup/oh-my-zsh/plugins/zsh-syntax-highlighting
```

Without ```-L```, ```upgrade_oh_my_zsh_custom``` cannot find any of the git repositories. 

I tested the updated find command with symlinked plugins and plugins in directories in the same plugins directory. It could find all repositories. Therefore, adding ```-L``` should be no issue for users without symlinks.

If you want to make it absolutely save, you could introduce a variable which overrides the behavior.

Thanks in advance.

**Comment by TamCore** [comment]
Sounds like a good idea. Even though I was worrying about different variants of find out there maybe not having the -L switch, it seems to work just find even on my Mac.

Thanks for your suggestion! :)

**Comment by ckotte** [comment]
thx
