### ISSUE TITLE
upgrade_oh_my_zsh marked as deprecated

### ISSUE THREAD

**Issue by PositivePaulo** [TamCore/autoupdate-oh-my-zsh-plugins#14]
It seems that the Oh My Zsh community decided to introduce a new `omz` command to centralize OMZ-related actions and moved the update mechanism to it: https://github.com/ohmyzsh/ohmyzsh/commit/3935ccce647c722bcfdaa771b01613079db20935. So now, when using this plugin's `upgrade_ohl_my_zsh` command which calls the old `upgrade_oh_my_zsh` function, it displays this:

![image](https://user-images.githubusercontent.com/35344098/90337562-8d55c480-dfe3-11ea-8d08-213a561b16f1.png)

Maybe consider replacing the call to the deprecated command with the new `omz update`?
Cheers.

**Comment by TamCore** [comment]
Done. Thank you for the heads up!
