### ISSUE TITLE
Add support for "main" default branch

### ISSUE THREAD

**Issue by seboudry** [TamCore/autoupdate-oh-my-zsh-plugins#19]
Some plugin repositories have renamed their `master` branch to `main`.
This autoupdate plugin should work on both configuration.

Thanks for this little but useful plugin ;)

**Comment by TamCore** [comment]
Should be addressed now. If I broke it instead, please let me know :)

**Comment by seboudry** [comment]
Works like a charm!

I was on doing a PR but you're quickier ;)
