### ISSUE TITLE
CI: Redundant Setup Python step

### ISSUE THREAD

**Issue by elliotwutingfeng** [tamcore/autoupdate-oh-my-zsh-plugins#28]
The following lines seem to be redundant as there are no python code in the repository.

https://github.com/tamcore/autoupdate-oh-my-zsh-plugins/blob/8c4f63db6a7a989f4eb8f8a3211bf96243e15bb9/.github/workflows/ci.yaml#L15-L16

**Comment by tamcore** [comment]
It's a requirement for pre-commit.
