### ISSUE TITLE
Can't make this work, either by calling `upgrade_oh_my_zsh` nor automatically

### ISSUE THREAD

**Issue by rsalmei** [TamCore/autoupdate-oh-my-zsh-plugins#8]
Hey man, could you help me?

I've cloned like you've said in the readme:
```zsh
❯ git clone https://github.com/TamCore/autoupdate-oh-my-zsh-plugins $ZSH_CUSTOM/plugins/autoupdate
```

My dir is now:
```
❯ ls $ZSH_CUSTOM/plugins/
autoupdate                   zsh-autosuggestions          zsh-syntax-highlighting
example                      zsh-history-substring-search
```

In my `.zshrc` I have:
```
plugins=(autoupdate pyenv zsh-autosuggestions history-substring-search z zsh-syntax-highlighting)
```

I've started another shell, but when I run upgrade it doesn't kick in:
```
❯ upgrade_oh_my_zsh
Updating Oh My Zsh
From https://github.com/ohmyzsh/ohmyzsh
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
         __                                     __
  ____  / /_     ____ ___  __  __   ____  _____/ /_
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/
                        /____/
Hooray! Oh My Zsh has been updated and/or is at the current version.
To keep up on the latest news and updates, follow us on twitter: https://twitter.com/ohmyzsh
Get your Oh My Zsh swag at: https://shop.planetargon.com/collections/oh-my-zsh
❯
```

I'm on macOS:
```
❯ zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

Can you imagine what is going on?

**Comment by liby** [comment]
It doesn't seem to be triggered by the `upgrade_oh_my_zsh` command.

I tried to run `zsh autoupdate.plugin.zsh` in the `${ZSH_CUSTOM}/plugins/autoupdate` directory and got the following error.
> _update_zsh_custom_update:1: read-only file system: /.zsh-custom-update

@TamCore 
I'd like to ask two questions:
  1. What is the trigger condition for the 'autoupdate-oh-my-zsh-plugins' to run?
  2. `echo "LAST_EPOCH=$(_current_epoch)" >! "${ZSH_CACHE_DIR}/.zsh-custom-update"`. What does this operator(`>!`) mean?

I have only seen two operators similar to the following:
> `command > file` redirects a command’s output to a file (overwriting any existing content).
> `command >> file` appends a command’s output to a file.

**Comment by TamCore** [comment]
The plugin, like oh-my-zsh, uses the variable UPDATE_ZSH_DAYS to determine, after how many days it should execute again. It's exactly the same way as oh-my-zsh itself handles it.

```bash
philipp@Philipps-MacBook-Pro.local ~ $ echo $UPDATE_ZSH_DAYS
1
philipp@Philipps-MacBook-Pro.local ~ $ echo LAST_EPOCH=1 >! $ZSH_CACHE_DIR/.zsh-custom-update
philipp@Philipps-MacBook-Pro.local ~ $ src
Upgrading custom plugins
From https://github.com/zsh-users/zsh-autosuggestions
 * branch            master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
Hooray! /Users/philipp/.oh-my-zsh/custom/plugins/zsh-autosuggestions/.git has been updated and/or is at the current version.
From https://github.com/zdharma/fast-syntax-highlighting
 * branch            master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
Hooray! /Users/philipp/.oh-my-zsh/custom/plugins/fast-syntax-highlighting/.git has been updated and/or is at the current version.
From https://github.com/TamCore/autoupdate-oh-my-zsh-plugins
 * branch            master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
Hooray! /Users/philipp/.oh-my-zsh/custom/plugins/autoupdate/.git has been updated and/or is at the current version.
(pwd now: ~/.oh-my-zsh/custom/plugins/autoupdate)
philipp@Philipps-MacBook-Pro.local ~ $
```

@liby Your manual execution of autoupdate.plugin.zsh failed, because it's not supposed to be run standalone and therefore requires certain environment-variables set by oh-my-zsh.

**Comment by TamCore** [comment]
Thanks to @PositivePaulo's PR #11, you can now manually invoke upgrade_oh_my_zsh_custom to trigger the process.
